[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
voting_system = "DKrPYCwiCPfCy2JHCeghPZj9BXZjWB2FA762D36eSLCd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/tony/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
